//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Arm Movement"",
            ""id"": ""88ded5e6-fb55-4a5e-ac8e-f8cc4d1b6998"",
            ""actions"": [
                {
                    ""name"": ""Base"",
                    ""type"": ""Button"",
                    ""id"": ""9814d60f-3985-4814-8a7c-a893ca2d8354"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoulder"",
                    ""type"": ""Button"",
                    ""id"": ""06cecaab-2e5a-494e-8666-f33833036d5d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Elbow"",
                    ""type"": ""Button"",
                    ""id"": ""263a0d81-8f2c-4014-add8-22e36faf9933"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Wrist1"",
                    ""type"": ""Button"",
                    ""id"": ""d5960daa-f5d7-4cd5-a739-9513432baf0f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Wrist2"",
                    ""type"": ""Button"",
                    ""id"": ""7f0e5fcb-2d9d-405d-8aab-ef251567dbe8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Wrist3"",
                    ""type"": ""Button"",
                    ""id"": ""e5016354-07ba-4a32-8c58-6d13f912eb31"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hand"",
                    ""type"": ""Button"",
                    ""id"": ""23a8fc95-f535-4019-9c04-d061f4ca3cb6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Fingers"",
                    ""type"": ""Button"",
                    ""id"": ""ddcd790d-974f-4d88-a515-e5b59601f6fa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Joystick"",
                    ""id"": ""20107dfc-f188-443c-ae44-563f6df1f60a"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Base"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""0eaf271a-6ead-48bd-bc8f-4a0c6bb5a809"",
                    ""path"": ""<DualShockGamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Base"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""20a53967-7245-4f31-8672-74ea00d38e73"",
                    ""path"": ""<DualShockGamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Base"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""cb81efd3-bcdf-476e-a37b-2125471a0068"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Base"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""4bbf5898-6968-4855-af64-27b9269ad09f"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Base"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""a37e5c82-acc3-4100-9ec8-6f92a2034c87"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Base"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Joystick"",
                    ""id"": ""e9eff57a-dec2-4d51-aad4-00a569772af3"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoulder"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""90639d3c-b291-46ef-93e5-38a673b4a05c"",
                    ""path"": ""<DualShockGamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoulder"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""98302a3a-ef9e-4f04-87db-d075c1da763e"",
                    ""path"": ""<DualShockGamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoulder"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""0641b07d-2410-40e5-85c3-ca88e0a5fee5"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoulder"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""30880339-ddef-49b9-b9b8-53cc6d935658"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoulder"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""ad01c1ef-103a-4056-a716-db7795e7399c"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoulder"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Joystick"",
                    ""id"": ""7fc5dc4c-fab6-48f3-8141-b1547bcb12e6"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Elbow"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""0877aa5d-5613-475d-86be-ae0a077cf06e"",
                    ""path"": ""<DualShockGamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Elbow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""92df817a-f819-4f7c-8096-97576738baa9"",
                    ""path"": ""<DualShockGamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Elbow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""ebc9fe88-1d91-4f7e-a525-2273a5c72753"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Elbow"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""8eda8f99-f2f0-434b-acfb-5f2d6fb13753"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Elbow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""2e36869f-fb9d-457e-8874-31e50eb2ed3e"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Elbow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Joystick"",
                    ""id"": ""ef4eae3e-bdcb-49e7-9a99-ff516c8db803"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wrist1"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""9e7b84d7-3769-444b-a855-b838b757f288"",
                    ""path"": ""<DualShockGamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wrist1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""9e8df59a-7617-4632-b8ad-d96e30ff376e"",
                    ""path"": ""<DualShockGamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wrist1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""79698b0f-e01f-4a7f-984f-6e98e2760d1d"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wrist1"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""95aef38e-fe5d-4c74-8428-cd8db8e43e17"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wrist1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""27bde04b-92b2-47ec-91f6-a6294a28ef95"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wrist1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Joystick"",
                    ""id"": ""036f6634-7e19-46b4-b9ce-bd3018118081"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wrist2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""f303f44c-1de4-4aa6-bd1b-40788ebf73bc"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wrist2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""cbd89d2b-e61e-4b43-a77d-314a1c10eb87"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wrist2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""2fe83b5c-0704-48ee-88a2-083fe84c6fb9"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wrist2"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""5f57fee5-2a24-450f-b785-971bff3fa0e4"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wrist2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""ebc617e6-924b-4f58-9cc0-1700a3007b5a"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wrist2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Joystcik"",
                    ""id"": ""a2c19693-db45-45ed-8a24-39e161f0ce54"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wrist3"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""fcab68ba-77fb-4612-ac33-4dce940f7d49"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wrist3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""dbedcfcc-b6d4-45d6-8ea9-d0257349b5d6"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wrist3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""65b89507-0f44-40b1-9ab4-7e924461cffb"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wrist3"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""bd3a0404-8ea5-4fd3-9620-7dd0ade119b4"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wrist3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""9fb86ce0-8fe6-4a8b-8a8e-a9210355317f"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Wrist3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Joystick"",
                    ""id"": ""1c5bed5a-24f6-4866-aeff-0a0c2b7910c5"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hand"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""1e9fa291-d9bd-4f7b-b0c8-31546292e4b9"",
                    ""path"": ""<DualShockGamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""e19ecd55-c88e-4955-9874-c1a0262f843f"",
                    ""path"": ""<DualShockGamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""ba30fe48-4339-4871-ab26-93701f6d5631"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hand"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""fdd92e1c-d5b1-49b2-883e-e2573bdf930b"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""ef1af219-e02c-460d-a751-2b4000b987ce"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hand"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Joystick"",
                    ""id"": ""49614ff4-b211-4561-a40e-3360cc87efd6"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fingers"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""d163b5a5-aea3-4401-be03-2dda1f311c2d"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fingers"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""343210ab-6975-40d5-b798-11625dd515d2"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fingers"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""150caadd-91c2-4255-86f8-940600ce1789"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fingers"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""e0e51e93-0952-4974-8ce8-dddbe1b43735"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fingers"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""ef82add0-a2f7-403b-bdd8-b2e3cc493a1f"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Fingers"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""Magnet"",
            ""id"": ""fdda7531-f9c5-4740-b955-0cd8bc28a862"",
            ""actions"": [
                {
                    ""name"": ""Attract"",
                    ""type"": ""Button"",
                    ""id"": ""666810a6-e47f-48eb-9428-ba8956e7ddc6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Stop"",
                    ""type"": ""Button"",
                    ""id"": ""bdce54cb-7d41-41dc-b152-b47722d13b8d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f99c2463-fc6e-4bbb-a4d9-80f36e03c3b4"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attract"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9860b3d1-09b9-4082-8515-7958df5eb431"",
                    ""path"": ""<DualShockGamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attract"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f0fd7ec5-77e8-4671-ae90-a454540378ec"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da28e110-42ea-4a61-bb29-a70227b6021e"",
                    ""path"": ""<DualShockGamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Stop"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Arm Movement
        m_ArmMovement = asset.FindActionMap("Arm Movement", throwIfNotFound: true);
        m_ArmMovement_Base = m_ArmMovement.FindAction("Base", throwIfNotFound: true);
        m_ArmMovement_Shoulder = m_ArmMovement.FindAction("Shoulder", throwIfNotFound: true);
        m_ArmMovement_Elbow = m_ArmMovement.FindAction("Elbow", throwIfNotFound: true);
        m_ArmMovement_Wrist1 = m_ArmMovement.FindAction("Wrist1", throwIfNotFound: true);
        m_ArmMovement_Wrist2 = m_ArmMovement.FindAction("Wrist2", throwIfNotFound: true);
        m_ArmMovement_Wrist3 = m_ArmMovement.FindAction("Wrist3", throwIfNotFound: true);
        m_ArmMovement_Hand = m_ArmMovement.FindAction("Hand", throwIfNotFound: true);
        m_ArmMovement_Fingers = m_ArmMovement.FindAction("Fingers", throwIfNotFound: true);
        // Magnet
        m_Magnet = asset.FindActionMap("Magnet", throwIfNotFound: true);
        m_Magnet_Attract = m_Magnet.FindAction("Attract", throwIfNotFound: true);
        m_Magnet_Stop = m_Magnet.FindAction("Stop", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Arm Movement
    private readonly InputActionMap m_ArmMovement;
    private IArmMovementActions m_ArmMovementActionsCallbackInterface;
    private readonly InputAction m_ArmMovement_Base;
    private readonly InputAction m_ArmMovement_Shoulder;
    private readonly InputAction m_ArmMovement_Elbow;
    private readonly InputAction m_ArmMovement_Wrist1;
    private readonly InputAction m_ArmMovement_Wrist2;
    private readonly InputAction m_ArmMovement_Wrist3;
    private readonly InputAction m_ArmMovement_Hand;
    private readonly InputAction m_ArmMovement_Fingers;
    public struct ArmMovementActions
    {
        private @PlayerControls m_Wrapper;
        public ArmMovementActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Base => m_Wrapper.m_ArmMovement_Base;
        public InputAction @Shoulder => m_Wrapper.m_ArmMovement_Shoulder;
        public InputAction @Elbow => m_Wrapper.m_ArmMovement_Elbow;
        public InputAction @Wrist1 => m_Wrapper.m_ArmMovement_Wrist1;
        public InputAction @Wrist2 => m_Wrapper.m_ArmMovement_Wrist2;
        public InputAction @Wrist3 => m_Wrapper.m_ArmMovement_Wrist3;
        public InputAction @Hand => m_Wrapper.m_ArmMovement_Hand;
        public InputAction @Fingers => m_Wrapper.m_ArmMovement_Fingers;
        public InputActionMap Get() { return m_Wrapper.m_ArmMovement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ArmMovementActions set) { return set.Get(); }
        public void SetCallbacks(IArmMovementActions instance)
        {
            if (m_Wrapper.m_ArmMovementActionsCallbackInterface != null)
            {
                @Base.started -= m_Wrapper.m_ArmMovementActionsCallbackInterface.OnBase;
                @Base.performed -= m_Wrapper.m_ArmMovementActionsCallbackInterface.OnBase;
                @Base.canceled -= m_Wrapper.m_ArmMovementActionsCallbackInterface.OnBase;
                @Shoulder.started -= m_Wrapper.m_ArmMovementActionsCallbackInterface.OnShoulder;
                @Shoulder.performed -= m_Wrapper.m_ArmMovementActionsCallbackInterface.OnShoulder;
                @Shoulder.canceled -= m_Wrapper.m_ArmMovementActionsCallbackInterface.OnShoulder;
                @Elbow.started -= m_Wrapper.m_ArmMovementActionsCallbackInterface.OnElbow;
                @Elbow.performed -= m_Wrapper.m_ArmMovementActionsCallbackInterface.OnElbow;
                @Elbow.canceled -= m_Wrapper.m_ArmMovementActionsCallbackInterface.OnElbow;
                @Wrist1.started -= m_Wrapper.m_ArmMovementActionsCallbackInterface.OnWrist1;
                @Wrist1.performed -= m_Wrapper.m_ArmMovementActionsCallbackInterface.OnWrist1;
                @Wrist1.canceled -= m_Wrapper.m_ArmMovementActionsCallbackInterface.OnWrist1;
                @Wrist2.started -= m_Wrapper.m_ArmMovementActionsCallbackInterface.OnWrist2;
                @Wrist2.performed -= m_Wrapper.m_ArmMovementActionsCallbackInterface.OnWrist2;
                @Wrist2.canceled -= m_Wrapper.m_ArmMovementActionsCallbackInterface.OnWrist2;
                @Wrist3.started -= m_Wrapper.m_ArmMovementActionsCallbackInterface.OnWrist3;
                @Wrist3.performed -= m_Wrapper.m_ArmMovementActionsCallbackInterface.OnWrist3;
                @Wrist3.canceled -= m_Wrapper.m_ArmMovementActionsCallbackInterface.OnWrist3;
                @Hand.started -= m_Wrapper.m_ArmMovementActionsCallbackInterface.OnHand;
                @Hand.performed -= m_Wrapper.m_ArmMovementActionsCallbackInterface.OnHand;
                @Hand.canceled -= m_Wrapper.m_ArmMovementActionsCallbackInterface.OnHand;
                @Fingers.started -= m_Wrapper.m_ArmMovementActionsCallbackInterface.OnFingers;
                @Fingers.performed -= m_Wrapper.m_ArmMovementActionsCallbackInterface.OnFingers;
                @Fingers.canceled -= m_Wrapper.m_ArmMovementActionsCallbackInterface.OnFingers;
            }
            m_Wrapper.m_ArmMovementActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Base.started += instance.OnBase;
                @Base.performed += instance.OnBase;
                @Base.canceled += instance.OnBase;
                @Shoulder.started += instance.OnShoulder;
                @Shoulder.performed += instance.OnShoulder;
                @Shoulder.canceled += instance.OnShoulder;
                @Elbow.started += instance.OnElbow;
                @Elbow.performed += instance.OnElbow;
                @Elbow.canceled += instance.OnElbow;
                @Wrist1.started += instance.OnWrist1;
                @Wrist1.performed += instance.OnWrist1;
                @Wrist1.canceled += instance.OnWrist1;
                @Wrist2.started += instance.OnWrist2;
                @Wrist2.performed += instance.OnWrist2;
                @Wrist2.canceled += instance.OnWrist2;
                @Wrist3.started += instance.OnWrist3;
                @Wrist3.performed += instance.OnWrist3;
                @Wrist3.canceled += instance.OnWrist3;
                @Hand.started += instance.OnHand;
                @Hand.performed += instance.OnHand;
                @Hand.canceled += instance.OnHand;
                @Fingers.started += instance.OnFingers;
                @Fingers.performed += instance.OnFingers;
                @Fingers.canceled += instance.OnFingers;
            }
        }
    }
    public ArmMovementActions @ArmMovement => new ArmMovementActions(this);

    // Magnet
    private readonly InputActionMap m_Magnet;
    private IMagnetActions m_MagnetActionsCallbackInterface;
    private readonly InputAction m_Magnet_Attract;
    private readonly InputAction m_Magnet_Stop;
    public struct MagnetActions
    {
        private @PlayerControls m_Wrapper;
        public MagnetActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Attract => m_Wrapper.m_Magnet_Attract;
        public InputAction @Stop => m_Wrapper.m_Magnet_Stop;
        public InputActionMap Get() { return m_Wrapper.m_Magnet; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MagnetActions set) { return set.Get(); }
        public void SetCallbacks(IMagnetActions instance)
        {
            if (m_Wrapper.m_MagnetActionsCallbackInterface != null)
            {
                @Attract.started -= m_Wrapper.m_MagnetActionsCallbackInterface.OnAttract;
                @Attract.performed -= m_Wrapper.m_MagnetActionsCallbackInterface.OnAttract;
                @Attract.canceled -= m_Wrapper.m_MagnetActionsCallbackInterface.OnAttract;
                @Stop.started -= m_Wrapper.m_MagnetActionsCallbackInterface.OnStop;
                @Stop.performed -= m_Wrapper.m_MagnetActionsCallbackInterface.OnStop;
                @Stop.canceled -= m_Wrapper.m_MagnetActionsCallbackInterface.OnStop;
            }
            m_Wrapper.m_MagnetActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Attract.started += instance.OnAttract;
                @Attract.performed += instance.OnAttract;
                @Attract.canceled += instance.OnAttract;
                @Stop.started += instance.OnStop;
                @Stop.performed += instance.OnStop;
                @Stop.canceled += instance.OnStop;
            }
        }
    }
    public MagnetActions @Magnet => new MagnetActions(this);
    public interface IArmMovementActions
    {
        void OnBase(InputAction.CallbackContext context);
        void OnShoulder(InputAction.CallbackContext context);
        void OnElbow(InputAction.CallbackContext context);
        void OnWrist1(InputAction.CallbackContext context);
        void OnWrist2(InputAction.CallbackContext context);
        void OnWrist3(InputAction.CallbackContext context);
        void OnHand(InputAction.CallbackContext context);
        void OnFingers(InputAction.CallbackContext context);
    }
    public interface IMagnetActions
    {
        void OnAttract(InputAction.CallbackContext context);
        void OnStop(InputAction.CallbackContext context);
    }
}
